require: rubocop-rspec
inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
AbcSize:
  Enabled: false
LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*'
    - 'db/migrate/*'
    - 'vendor/**/*'
  RunRailsCops: true
