cache: bundler
language: ruby
rvm:
  - 2.2.2
notifications:
  email: rue

addons:
  posgresql: '9.1'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
 - xvfb-run bundle exec rspec
 - bundle exec rubocop
